### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by vlcty** [misiupajor/check_elasticsearch#14]
When running the script it gives me a

> TabError: inconsistent use of tabs and spaces in indentation

Python 3.9.5 in a naked venv.

**Comment by sebbele** [comment]
@vlcty did you possibly copy-paste into some editor? Or did you clone the repo?

**Comment by vlcty** [comment]
Cloned the repo. No alterations done.

**Comment by sebbele** [comment]
@vlcty I can see the inconsistent tabs are at line 105 and 106, it needs to be replaced with spaces. It could use a PR fix, but if you want to quickly fix it you could do it like this:
`sed -i 's/\t/        /g' check_elasticsearch.py`
Note, it's 8 spaces at the `t/        /g` part but github makes it look like 1 space.
